In [1]:
import pandas as pd

In [3]:
df =pd.read_excel('customer_data.xlsx')
df

      customer_id  gender   age payment_method
0         C241288  Female  28.0    Credit Card
1         C111565    Male  21.0     Debit Card
2         C266599    Male  20.0           Cash
3         C988172  Female  66.0    Credit Card
4         C189076  Female  53.0           Cash
...           ...     ...   ...            ...
99452     C441542  Female  45.0    Credit Card
99453     C569580    Male  27.0           Cash
99454     C103292    Male  63.0     Debit Card
99455     C800631    Male  56.0           Cash
99456     C273973  Female  36.0    Credit Card

[99457 rows x 4 columns]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     99457 non-null  str
 1   gender          99457 non-null  str
 2   age             99338 non-null  float64
 3   payment_method  99457 non-null  str
dtypes: float64(1), str(3)
memory usage: 4.9 MB

In [5]:
df.isnull().sum()

customer_id         0
gender              0
age               119
payment_method      0
dtype: int64

In [6]:
df['age'].fillna(df['age'].mean(), inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_5204\1503503937.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['age'].fillna(df['age'].mean(), inplace=True)

0        28.0
1        21.0
2        20.0
3        66.0
4        53.0
         ...
99452    45.0
99453    27.0
99454    63.0
99455    56.0
99456    36.0
Name: age, Length: 99457, dtype: float64

In [7]:
gg = pd.read_excel('sales_data.xlsx')
gg

,invoice_no,customer_id,category,quantity,invoice date,price,shopping_mall
0,I138884,C241288,Clothing,5,05/08/2022,1500.40,South Coast Plaza
1,I317333,C111565,Shoes,3,12/12/2021,1800.51,Beverly Center
2,I127801,C266599,Clothing,1,09/11/2021,300.08,Westfield Century City
3,I173702,C988172,Shoes,5,05/16/2021,3000.85,Stanford Shopping Center
4,I337046,C189076,Books,4,10/24/2021,60.60,South Coast Plaza
...,...,...,...,...,...,...,...
99452,I219422,C441542,Souvenir,5,09/21/2022,58.65,South Coast Plaza
99453,I325143,C569580,Food & Beverage,2,09/22/2021,10.46,Beverly Center
99454,I824010,C103292,Food & Beverage,2,03/28/2021,10.46,Westfield Century City
99455,I702964,C800631,Technology,4,03/16/2021,4200.00,Westfield Valley Fair
99456,I232867,C273973,Souvenir,3,10/15/2022,35.19,Del Amo Fashion Center

In [8]:
gg['invoice date'].fillna(gg['invoice date'].mode()[0], inplace = True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_5204\2956079787.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  gg['invoice date'].fillna(gg['invoice date'].mode()[0], inplace = True)

0        05/08/2022
1        12/12/2021
2        09/11/2021
3        05/16/2021
4        10/24/2021
            ...
99452    09/21/2022
99453    09/22/2021
99454    03/28/2021
99455    03/16/2021
99456    10/15/2022
Name: invoice date, Length: 99457, dtype: str

In [9]:
gg['invoice date'].rename('invoice_date' , inplace= True)

0        05/08/2022
1        12/12/2021
2        09/11/2021
3        05/16/2021
4        10/24/2021
            ...
99452    09/21/2022
99453    09/22/2021
99454    03/28/2021
99455    03/16/2021
99456    10/15/2022
Name: invoice_date, Length: 99457, dtype: str

In [10]:
gg['invoice_no'].duplicated().sum()

np.int64(0)

In [11]:
gg

,invoice_no,customer_id,category,quantity,invoice date,price,shopping_mall
0,I138884,C241288,Clothing,5,05/08/2022,1500.40,South Coast Plaza
1,I317333,C111565,Shoes,3,12/12/2021,1800.51,Beverly Center
2,I127801,C266599,Clothing,1,09/11/2021,300.08,Westfield Century City
3,I173702,C988172,Shoes,5,05/16/2021,3000.85,Stanford Shopping Center
4,I337046,C189076,Books,4,10/24/2021,60.60,South Coast Plaza
...,...,...,...,...,...,...,...
99452,I219422,C441542,Souvenir,5,09/21/2022,58.65,South Coast Plaza
99453,I325143,C569580,Food & Beverage,2,09/22/2021,10.46,Beverly Center
99454,I824010,C103292,Food & Beverage,2,03/28/2021,10.46,Westfield Century City
99455,I702964,C800631,Technology,4,03/16/2021,4200.00,Westfield Valley Fair
99456,I232867,C273973,Souvenir,3,10/15/2022,35.19,Del Amo Fashion Center

In [12]:
gg.isnull().sum()

invoice_no       0
customer_id      0
category         0
quantity         0
invoice date     0
price            0
shopping_mall    0
dtype: int64

In [13]:
df.isnull().sum()

customer_id         0
gender              0
age               119
payment_method      0
dtype: int64

In [14]:
df['age'] = df['age'].fillna(df['age'].mean())

In [15]:
df['age'].head()

0    28.0
1    21.0
2    20.0
3    66.0
4    53.0
Name: age, dtype: float64

In [16]:
df.isnull().sum()

customer_id       0
gender            0
age               0
payment_method    0
dtype: int64

In [17]:
df.to_csv('customer_data.csv' , index= False)

In [18]:
gg.to_csv('sales_data.csv' , index = False)

In [19]:
rr = pd.read_csv('customer_data.csv')
rr

      customer_id  gender   age payment_method
0         C241288  Female  28.0    Credit Card
1         C111565    Male  21.0     Debit Card
2         C266599    Male  20.0           Cash
3         C988172  Female  66.0    Credit Card
4         C189076  Female  53.0           Cash
...           ...     ...   ...            ...
99452     C441542  Female  45.0    Credit Card
99453     C569580    Male  27.0           Cash
99454     C103292    Male  63.0     Debit Card
99455     C800631    Male  56.0           Cash
99456     C273973  Female  36.0    Credit Card

[99457 rows x 4 columns]

In [20]:
ff = pd.read_csv('sales_data.csv')
ff

,invoice_no,customer_id,category,quantity,invoice date,price,shopping_mall
0,I138884,C241288,Clothing,5,05/08/2022,1500.40,South Coast Plaza
1,I317333,C111565,Shoes,3,12/12/2021,1800.51,Beverly Center
2,I127801,C266599,Clothing,1,09/11/2021,300.08,Westfield Century City
3,I173702,C988172,Shoes,5,05/16/2021,3000.85,Stanford Shopping Center
4,I337046,C189076,Books,4,10/24/2021,60.60,South Coast Plaza
...,...,...,...,...,...,...,...
99452,I219422,C441542,Souvenir,5,09/21/2022,58.65,South Coast Plaza
99453,I325143,C569580,Food & Beverage,2,09/22/2021,10.46,Beverly Center
99454,I824010,C103292,Food & Beverage,2,03/28/2021,10.46,Westfield Century City
99455,I702964,C800631,Technology,4,03/16/2021,4200.00,Westfield Valley Fair
99456,I232867,C273973,Souvenir,3,10/15/2022,35.19,Del Amo Fashion Center

In [21]:
merge = pd.merge(rr , ff , left_on='customer_id' , right_on ='customer_id' , how = 'inner')

In [22]:
merge

,customer_id,gender,age,payment_method,invoice_no,category,quantity,invoice date,price,shopping_mall
0,C241288,Female,28.0,Credit Card,I138884,Clothing,5,05/08/2022,1500.40,South Coast Plaza
1,C111565,Male,21.0,Debit Card,I317333,Shoes,3,12/12/2021,1800.51,Beverly Center
2,C266599,Male,20.0,Cash,I127801,Clothing,1,09/11/2021,300.08,Westfield Century City
3,C988172,Female,66.0,Credit Card,I173702,Shoes,5,05/16/2021,3000.85,Stanford Shopping Center
4,C189076,Female,53.0,Cash,I337046,Books,4,10/24/2021,60.60,South Coast Plaza
...,...,...,...,...,...,...,...,...,...,...
99452,C441542,Female,45.0,Credit Card,I219422,Souvenir,5,09/21/2022,58.65,South Coast Plaza
99453,C569580,Male,27.0,Cash,I325143,Food & Beverage,2,09/22/2021,10.46,Beverly Center
99454,C103292,Male,63.0,Debit Card,I824010,Food & Beverage,2,03/28/2021,10.46,Westfield Century City
99455,C800631,Male,56.0,Cash,I702964,Technology,4,03/16/2021,4200.00,Westfield Valley Fair
99456,C273973,Female,36.0,Credit Card,I232867,Souvenir,3,10/15/2022,35.19,Del Amo Fashion Center

In [23]:
total_revenue = merge['quantity']* merge['price']
merge['total_revenue'] = total_revenue
merge

,customer_id,gender,age,payment_method,invoice_no,category,quantity,invoice date,price,shopping_mall,total_revenue
0,C241288,Female,28.0,Credit Card,I138884,Clothing,5,05/08/2022,1500.40,South Coast Plaza,7502.00
1,C111565,Male,21.0,Debit Card,I317333,Shoes,3,12/12/2021,1800.51,Beverly Center,5401.53
2,C266599,Male,20.0,Cash,I127801,Clothing,1,09/11/2021,300.08,Westfield Century City,300.08
3,C988172,Female,66.0,Credit Card,I173702,Shoes,5,05/16/2021,3000.85,Stanford Shopping Center,15004.25
4,C189076,Female,53.0,Cash,I337046,Books,4,10/24/2021,60.60,South Coast Plaza,242.40
...,...,...,...,...,...,...,...,...,...,...,...
99452,C441542,Female,45.0,Credit Card,I219422,Souvenir,5,09/21/2022,58.65,South Coast Plaza,293.25
99453,C569580,Male,27.0,Cash,I325143,Food & Beverage,2,09/22/2021,10.46,Beverly Center,20.92
99454,C103292,Male,63.0,Debit Card,I824010,Food & Beverage,2,03/28/2021,10.46,Westfield Century City,20.92
99455,C800631,Male,56.0,Cash,I702964,Technology,4,03/16/2021,4200.00,Westfield Valley Fair,16800.00
99456,C273973,Female,36.0,Credit Card,I232867,Souvenir,3,10/15/2022,35.19,Del Amo Fashion Center,105.57

In [24]:
age_group = merge['age'].apply(lambda x: 'young' if x< 30 else 'middle-aged' if x <50 else 'senior')
merge['age_group'] = age_group
merge

,customer_id,gender,age,payment_method,invoice_no,category,quantity,invoice date,price,shopping_mall,total_revenue,age_group
0,C241288,Female,28.0,Credit Card,I138884,Clothing,5,05/08/2022,1500.40,South Coast Plaza,7502.00,young
1,C111565,Male,21.0,Debit Card,I317333,Shoes,3,12/12/2021,1800.51,Beverly Center,5401.53,young
2,C266599,Male,20.0,Cash,I127801,Clothing,1,09/11/2021,300.08,Westfield Century City,300.08,young
3,C988172,Female,66.0,Credit Card,I173702,Shoes,5,05/16/2021,3000.85,Stanford Shopping Center,15004.25,senior
4,C189076,Female,53.0,Cash,I337046,Books,4,10/24/2021,60.60,South Coast Plaza,242.40,senior
...,...,...,...,...,...,...,...,...,...,...,...,...
99452,C441542,Female,45.0,Credit Card,I219422,Souvenir,5,09/21/2022,58.65,South Coast Plaza,293.25,middle-aged
99453,C569580,Male,27.0,Cash,I325143,Food & Beverage,2,09/22/2021,10.46,Beverly Center,20.92,young
99454,C103292,Male,63.0,Debit Card,I824010,Food & Beverage,2,03/28/2021,10.46,Westfield Century City,20.92,senior
99455,C800631,Male,56.0,Cash,I702964,Technology,4,03/16/2021,4200.00,Westfield Valley Fair,16800.00,senior
99456,C273973,Female,36.0,Credit Card,I232867,Souvenir,3,10/15/2022,35.19,Del Amo Fashion Center,105.57,middle-aged

In [25]:
month = pd.to_datetime(merge['invoice date']).dt.month
year = pd.to_datetime(merge['invoice date']).dt.year
merge['month']= month
merge['year']= year
merge

,customer_id,gender,age,payment_method,invoice_no,category,quantity,invoice date,price,shopping_mall,total_revenue,age_group,month,year
0,C241288,Female,28.0,Credit Card,I138884,Clothing,5,05/08/2022,1500.40,South Coast Plaza,7502.00,young,5,2022
1,C111565,Male,21.0,Debit Card,I317333,Shoes,3,12/12/2021,1800.51,Beverly Center,5401.53,young,12,2021
2,C266599,Male,20.0,Cash,I127801,Clothing,1,09/11/2021,300.08,Westfield Century City,300.08,young,9,2021
3,C988172,Female,66.0,Credit Card,I173702,Shoes,5,05/16/2021,3000.85,Stanford Shopping Center,15004.25,senior,5,2021
4,C189076,Female,53.0,Cash,I337046,Books,4,10/24/2021,60.60,South Coast Plaza,242.40,senior,10,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99452,C441542,Female,45.0,Credit Card,I219422,Souvenir,5,09/21/2022,58.65,South Coast Plaza,293.25,middle-aged,9,2022
99453,C569580,Male,27.0,Cash,I325143,Food & Beverage,2,09/22/2021,10.46,Beverly Center,20.92,young,9,2021
99454,C103292,Male,63.0,Debit Card,I824010,Food & Beverage,2,03/28/2021,10.46,Westfield Century City,20.92,senior,3,2021
99455,C800631,Male,56.0,Cash,I702964,Technology,4,03/16/2021,4200.00,Westfield Valley Fair,16800.00,senior,3,2021
99456,C273973,Female,36.0,Credit Card,I232867,Souvenir,3,10/15/2022,35.19,Del Amo Fashion Center,105.57,middle-aged,10,2022

In [26]:
merge.to_csv('mall_customer_data.csv' , index = False)